# Generated by Django 4.1 on 2022-09-19 22:47

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePost', models.CharField(max_length=50, verbose_name='Category')),
                ('titlePost', models.CharField(max_length=120, verbose_name='Title')),
                ('descriptionPost', models.CharField(max_length=220, verbose_name='Description')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='articles', variations={'thumbnail': {'crop': True, 'height': 330, 'width': 292}})),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentPost', models.TextField(verbose_name='Content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posts')),
            ],
        ),
    ]
