# Generated by Django 4.1 on 2022-09-20 07:09

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProfile', models.CharField(max_length=100, verbose_name='Nome')),
                ('gitLink', models.CharField(max_length=100, verbose_name='Git')),
                ('linkedinLink', models.CharField(max_length=100, verbose_name='Linkedin')),
                ('congratulation', models.CharField(max_length=200, verbose_name='Congratulation')),
                ('apresentation', models.CharField(max_length=200, verbose_name='Apresentation')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='articles', variations={'thumbnail': {'crop': True, 'height': 330, 'width': 292}})),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug')),
            ],
        ),
    ]
