# Generated by Django 4.1 on 2022-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='hello',
            field=models.CharField(default=1, max_length=50, verbose_name='Hello'),
            preserve_default=False,
        ),
    ]
