# Generated by Django 4.1 on 2022-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_emailprofile_profile_locate_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.TextField(default=1, verbose_name='History'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default=1, max_length=100, verbose_name='Instagram'),
            preserve_default=False,
        ),
    ]
